import React from 'react'
import { useNavigate } from 'react-router-dom'
import { ROUTES } from '../../routes/RouterConfig'

import History from '../../components/About/History'
import Collaboration from "../../components/About/Collaboration"
import './About.css'
import Flower from './flower.png'
import Footer from '../../components/Footer/Footer.jsx'
import Flow from '../../assets/Flower.png'
import Text from '../../components/Text/Text'
import Test1 from '../../assets/AboutImages/test1.png'
import Test2 from '../../assets/AboutImages/test2.png'
import Test3 from '../../assets/AboutImages/test3.png'


const About = () => {

  const navigate = useNavigate()

  const changeDir = (dir) => {
    navigate(dir)
  }
  const Testimonials = [
    {
      img: Test1,
      Testimonial: "Great working experieance .would love to work again. Totally satisfied with the work",
    },
    {
      img: Test2,
      Testimonial: "Great working experieance .would love to work again. Totally satisfied with the work",
    },
    {
      img: Test3,
      Testimonial: "Great working experieance .would love to work again. Totally satisfied with the work",
    }
  ]
  return (
    <>
      <div className="Navbox">
        <div className='iucee-heading'>
          <h2 className='iucee-title'>IUCEE</h2>
          <div className='home-about'>
            <h5 className="home99 ">Home >> About</h5>
          </div>

        </div>
        <img src={Flower} className="FlowerBG" ></img>
        <History className="Hist_and_Vision" /><br></br>
        <img src={Flow} alt="FlowerBG" className='Flow1'></img>
        <Collaboration />
        <div className='Annual'>
          <Text above="ANNUAL REPORTS" ma="ANNUAL REPORTS" />
          <div className='Report_display'><h6 className='Report_heading'>IUCEE Annual Report</h6>
            <p>
              Indo Universal Collaboration for Engineering Education (IUCEE)
              has been working effortlessly from past 13 years to evolve an ecosystem to
              enhance the quality of engineering education in India. Every year it publishes an
              annual report that provides detail information regarding various programs and events
              conducted by IUCEE, participation of various institutions, and number of papers published
              in IUCEE Annual Conference and Journal (JEET). IUCEE is a non-profit organization that
              solely functions on the funds generated by membership funds. Last year, the total income
              generated by IUCEE was $225, 000 and total expenses were $266,000. For details on IUCEE and
              its initiatives, refer the attached annual report.

            </p>
          </div>

          <button className='Download'>DOWNLOAD ANNUAL REPORT</button>

        </div>

        <div className='testimonial'>
          <Text above="TESTIMONIALS" ma="TESTIMONIALS" />
          <div className='Outertest_display'>
            {/* Comma Image  */}

            <div className='testimonial_display'>
              {Testimonials.map(testim => {
                return (
                  <div className='test_ind'>
                    <img src={testim.img} alt="Image" ></img>
                    <div>
                      <p>{testim.Testimonial}</p>
                    </div>
                  </div>
                )
              })}
            </div>

            <div>
              <button className='Download'>SUBMIT YOUR FEEDBACK</button>
            </div>
          </div>

        </div>
        <Footer/>
    
      </div>

    </>
  )
}

export default About